version: '3.8'

services:

    influxdb:
        image: influxdb:2.6-alpine
        container_name: "bhts_influxdb"
        env_file:
            - .env
        ports:
            - 8086:8086
        # volumes:
        #     - ./data/influxdb:/var/lib/influxdb

    grafana:
        image: grafana/grafana-oss:latest
        container_name: "bhts_grafana"
        user: '472'
        env_file:
            - .env
        ports:
            - 3000:3000
        volumes:
            - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
            # - ./dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
            # - ./dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
        links:
            - influxdb
        depends_on:
            - influxdb
