version: '3.8'

services:

    influxdb:
        image: influxdb:2.6-alpine
        container_name: "temp_influxdb"
        env_file:
            - .env
        ports:
            - '8086:8086'
        volumes:
            - ./data/influxdb:/var/lib/influxdb

    grafana:
        image: grafana/grafana-oss
        container_name: "temp_grafana"
        env_file:
            - .env
        ports:
            - '3000:3000'
        # volumes:
            # - ./data/grafana:/var/lib/grafana
        links:
            - influxdb
        depends_on:
            - influxdb